### ISSUE TITLE
Objektdefinition

### ISSUE THREAD

**Issue by Jey-Cee** [Zefau/ioBroker.hue-extended#1]
Hallo Zefau,

bitte folgende Punkte noch anpassen wenn nicht schon erledigt erledigt:
brightness und level zusammenführen in brightness, Wertbereich 0-100 mit der Einheit %.
color temperature Wertbereich 0-8000 ohne Einheit.
hue Wertebereich 0-360 in der Einheit °.
color RGB entfernen und in einzelne Kanäle auf teilen, damit lässt sich auch RGBW ode W alleine Abbilden.
Farbsysteme CIE und CMYK entfernen, wenn nötig intern umrechnen.
IDs ausschreiben also statt bri brightness, sat saturation usw.

**Comment by Zefau** [comment]
Wie passe ich in den ioBroker Objekten Wertebereiche an?

- brightness und level zusammenführen: Ist bewusst getrennt, da die User danach gefragtr haben.
- hue ist kein °, dafür gibt es hue_degrees (hue kommt direkt von der Hue API und ist ein Integer im Bereich bis 65k)
- RGB ist bewusst zusammengefasst drin. R, G und B einzeln würde bedeuten, dass im Zweifel 3 Befehle an die Lampen geschickt werden, statt nur einem Befehl
- die zusätzlichen Farbsysteme sind Features für den User und haben intern keine Bedeutung
- IDs ausschreiben würde ich ungern, da ich diese direkt vo der API übernehme ohne zusätzliche Berechnungen / Umrechnungen.

Alles in allem passe ich gerne die Wertebereiche für States / Objekte an, wenn ich weiß wie es geht und füge die Einheiten hinzu.

Cheers,
Zefau

**Comment by Zefau** [comment]
Wertebereiche mittels `min`, `max`, siehe https://www.iobroker.net/#en/documentation/dev/objectsschema.md?attributesforspecificobjecttypes

**Comment by Zefau** [comment]
Diskussion im Forum: https://forum.iobroker.net/topic/24936/diskussion-objektdefinition-licht/1

**Comment by Zefau** [comment]
Diskussion im Thread: https://forum.iobroker.net/topic/24207/neuer-adapter-hue-extended/239

**Comment by Zefau** [comment]
1. ~~Umbenennung von `bri` in `brightness`~~ Entfernen des Datenpunkts `bri` (brightness) (zur Steuerung verbleibt dann `level`)
2. Umbenennung von `sat` in `saturation`
3. Entfernen des Datenpunkts `hue` (Wert von 0 bis 65535) und Umbenennung von `hue_degrees` (Wert von 0° bis 360°) in `hue`
4. Alle Datenpunkte für die Farbräume entfernen (`_rgb`, `_hsv`, `_cmyk` und `_xyz`)
5. Einzelne Datenpunkte des RGB-Farbraums aufnehmen (`red`, `green` und `blue` )
6. Umbenennen von `_hex` in `hex`
7. Umbenennen von `ct` in `colorTemperature`

**Comment by Apollon77** [comment]
Hm ..,rgb wirklich auftrennen? Macht das sinn?
Ich persönlich bin eher bei einer Hex Abbildung als #rrggbb ... das wird vom iot Beispielsweise Unterstüztzt. getrennte Werte nicht
@Jey-Cee

**Comment by Zefau** [comment]
Changed with `v1.0.0-rc.1`.

- changed `bri` to `brightness`
- changed `sat` to `saturation`
- removed `hue_degrees`
- changed `hue` (changed value range from 0-65535 (native Hue API) to 0-360°C)
- changed `ct` to `colorTemperature`* (changed value range from 153-500 (native Hue API) to 2000-6500K)
- changed `_hex` to `hex`
- changed `_hsv` to `hsv`
- changed `_rgb` to `rgb`
- removed `_cmyk`
- removed `_xyz`
