### ISSUE TITLE
kelvin for ct, why not longer reciprocal megakelvin?

### ISSUE THREAD

**Issue by dercaptainbc** [Zefau/ioBroker.hue-extended#10]
Why we use kelvin values for colorTemperature and not longer reciprocal megakelvin?
Because on hue api side we use reciprocal megakelvin. (
I think its more a question ... or maybe a bug?

**Comment by Zefau** [comment]
This is due to https://github.com/Zefau/ioBroker.hue-extended/issues/1

**Comment by dercaptainbc** [comment]
... but I guess there is an error. 

I try to set `{"on":true,"bri":127,"ct":154}` 
colorTemperature have been set to 500 K and after some time it will changed to the old value 2000K

**Comment by dercaptainbc** [comment]
**Version is 1.1.2**

**Comment by dercaptainbc** [comment]
Quelle|Zeit|debug|Meldung
-- | -- | -- | --
hue-extended.0 | 2019-10-31 15:03:41.002 | info | (29578) Attempt 1x - Successfully set Wohnzimmer.
hue-extended.0 | 2019-10-31 15:03:41.002 | debug | (29578) Successfully set /groups/3/action/ct on Wohnzimmer (to 500).
hue-extended.0 | 2019-10-31 15:03:41.000 | debug | (29578) Successfully set /groups/3/action/bri on Wohnzimmer (to 127).
hue-extended.0 | 2019-10-31 15:03:40.999 | debug | (29578) Successfully set /groups/3/action/on on Wohnzimmer (to true).
hue-extended.0 | 2019-10-31 15:03:40.920 | debug | (29578) Attempt 1x - Send commands to Wohnzimmer (groups/3/action): {"on":true,"bri":127,"ct":500}.
hue-extended.0 | 2019-10-31 15:03:40.919 | debug | (29578) State of hue-extended.0.groups.003-wohnzimmer.action._commands has changed {"val":"{\"on\":true,\"bri\":127,\"ct\":154}","ack":false,"ts":1572530620913,"q":0,"from":"system.adapter.admin.0","u

**Comment by Zefau** [comment]
Thanks for reporting. This indeed looks incorrect.

**Comment by Zefau** [comment]
Could you try and install `v1.1.5` from Github and verify whether this is fixed?

**Comment by dercaptainbc** [comment]
confirmed! Issue is fixed for me.

**Comment by dercaptainbc** [comment]
just a little side note : 

reciprocal megakelvin | kelvin | calulated kelvin
-- | -- | -- 
370 | 2700 | 2703
333 | 3000 | 3003
250 | 4000 | 4000
182 | 5500 | 5495
154 | 6500 | 6494

maybe you can fix that, but its not urgent for me. JFYI

**Comment by Zefau** [comment]
hm... taking 370 it would be 1/370 = 0,0027027027027027 * 1000 * 1000 = 2702,702702702703 = rounded to 2703

**Comment by Zefau** [comment]
2700 back would be 370,3703703703704
