### ISSUE TITLE
Please use only valid versions in news

### ISSUE THREAD

**Issue by GermanBluefox** [Zefau/ioBroker.hue-extended#12]
https://github.com/Zefau/ioBroker.hue-extended/blob/master/io-package.json#L19
not allowed

**Comment by Zefau** [comment]
Confusing to be honest, since it is called `news` not `versions`.

**Comment by Zefau** [comment]
Will be removed with `v1.1.5` (https://github.com/Zefau/ioBroker.hue-extended/commit/51d346c0d920b3dc1374ee33805d0e706be6959a). Please rethink though if it is better to introduced something called `versions` for recent versions instead of `news`.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.hue-extended/releases/tag/v1.1.5
