### ISSUE TITLE
Update problem?

### ISSUE THREAD

**Issue by senger1985** [Zefau/ioBroker.hue-extended#13]
Iobroker shows me an update to v 2.0.1.
But only the v 1.1.0-beta.1 will be installed

**Comment by Zefau** [comment]
Thanks for reporting this. I'm aware of it.
I opened an issue at iobroker (https://github.com/ioBroker/ioBroker.repositories/issues/535), because it is actually not a error of this adapter.

**Comment by Zefau** [comment]
Should be fixed now. Can you confirm? Probably have to refresh adapters (`iobroker update`).

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/324703
