### ISSUE TITLE
Can't create new user

### ISSUE THREAD

**Issue by GerryHarrison** [Zefau/ioBroker.hue-extended#15]
Tried to create / add new user. Inserted IP-address, port 80 without SSL. Clicked on new user. Then pressed the button at the bridge and then clicked "neuen Benutzer abrufen". 
Error message:
Status:
Verbinde zum Adapter..
Verbunden zum Adapter. Lade Token..
Error: connect ECONNREFUSED 192.168.178.22
What might be the issue? Version 1.1.7
thanks a lot in advance

**Comment by Zefau** [comment]
I tried both using secure and non-secure connection. Both works perfectly fine for me and I successfully retrieved a new user / token.

You could try the CLIP API Debugger via https://192.168.178.22/debug/clip.html
- **URL** is only `/api/` (remove the numbers)
- **Message Body** is `{ 'devicetype': 'iobroker.hue-extended' }`

then press `POST`.

Does that work for you?

**Comment by GerryHarrison** [comment]
it worked! Thank you for the quick help and reply. And I really like the extended adapter,  much better overview, great work!
