### ISSUE TITLE
Changing brightness of a group turns on all the lights in the group

### ISSUE THREAD

**Issue by daniel1v** [Zefau/ioBroker.hue-extended#16]
Changing the /actions/bri attribute of a light group (a room for example) turns on all the lights of that group and then sets the value. While this behavior seems logical at first glance, it differs from the behavior of the official hue REST API. Here the change only affects the lights which are already on while other lights are kept off. 

I cross checked this behavior with the CLIP API Debugger and the official HUE App.

After short investigation I think the issue is that the adapter not only changes the brightness, but also sets the "on" state of the group to "true".

Here a practical use case: Five lights out of eight in my living room are already turned on and I want to dim them down because I want to watch TV. This could be achieved very easily by setting the brightness attribute of the group. The problem is: all eight lights in the room are turned on".

**Comment by Zefau** [comment]
Thanks for the detailed report. I saw you have implemented a solution in your fork. Would your pr the changes?

**Comment by daniel1v** [comment]
Hi, thank you for your reply. I tried to solve the issue but did not get it to work properly. Unfortunately I do not have much time to work on it at the moment but I will make a pr as soon as it works.

**Comment by daniel1v** [comment]
To be more precise: I came over a few issues when I tried to dive deeper into the HUE API and how group brightness changes are processed.

My goal was to get a behavior similar to the way the official Hue App handles group brightness changes. So I decided to analyze the exact behavior first. Here a short summary:

- If all lights are off:        
-- Group brightness value is zero / off
-- Changing group brightness is not possible as the slider disappears

- If one ore more lights are on:   
-- Group brightness in the app is calculated as the average brightness of **all turned on lights**.
-- Changing group brightness has following effects:
--- It changes the brightness of _all turned on lights_ and lets other lights turned off. 
--- The brightness is **not** set to a particular value. Rather the brightness of every single light is calculated separately. Every value changed proportionally so that the average matches the desired group brightness.

This sounds a bit complicated, but it is the most intuitive and comfortable way to go in my opinion (from the view of the end-user).

The big issue here is, that simply sending a group brightness value to the bridge API results in a very different behavior. Furthermore it seems like the above behavior cannot be achieved by setting this value. (And, as I recognized in further tests: the group brightness seems to be implemented a bit "dirty" on the hue bridge in my opinion). 

It seems that there is only _one specific light_, which defines the value of the group brightness. Other lights are not taken into account.

Here a short summary of the resulting behavior, using CLIP API Debugger:

- All lights are off:
-- Group brightness value represents the brightness value of the _one specific light_. 
-- Sending a group brightness value to the bridge does not have any effect. It does not turn on any light and also does not change any values, neither the value in the group nor the values of the lights.

One ore more lights are on:
-- Group brightness value is defined by the brightness value of  the_one specific light_. Also if this light is turned off.
-- Sending a group brightness value to the bridge sets all corresponding lights to that brightness, if they are turned on. Turned off lights are not affected in any way. The big issue: If the state of that _one specific light_ is "off", the brightness value of this light and also of the group itself remains the same, while the bridge changes the brightness of the lights.

Taking all that into account, I think the current behavior of your adapter is better than the inconsistent behavior of the bridge. Turning on all the lights, when brightness is changed, circumvents the inconsistencies, because the _one specific_ light is on and the group brightness value is set correctly. Furthermore I think it is the only way to directly make use of the group brightness value on the bridge, without running into the issues I described.

Nevertheless, a behavior similar to the hue app would be much more useful (in my opinion). This would afford a completely different logic, which does not rely on the group brightness value on the bridge, but rather an "artificial" group brightness value which is determined from the brightness values of the corresponding lights.

I will try to write a working code example (I'm an absolute beginner with JavaScript and also with ioBroker).

**Comment by Zefau** [comment]
Thanks for your deep and detailed analysis.

Sounds confusing to me to take the average brightness of a group. That's an interesting implementation made by hue. What if I want to set the whole group to one specific level?

Generally the question is, if any action / command shall only be applied on lights in a group that are turned on? The discussion is actually not only for brightness.

I could change the adapter behaviour to only change the brightness of lights if they are turned on. As an the user though I'm wondering how to turn on the lights that are off?

**Comment by daniel1v** [comment]
Yes, it's a bit confusing and I don't know if this implementation fits best for everyone. (for me it does) But I see, every method seems to have some advantages and also some drawbacks.

If more than one light in a group is "on", you can not set all the lights to set a specific level with one slide. first you have to slide it up to 100% or down to 0%, because then all single lights get the same level. from now on changes in the group are distributed 1:1 to the single lights. For a better understanding here some examples with 2 lights.

1. first we directly set the individual light levels:
- light1: 25% 
- light2: 75% 
--> result for group slider: 50% 
explanation: the average of 25% and 75% is 50%

2. now let's change group level:
- group slider: 75%
--> results for single lights: 
- light1: 65%
- light2: 85% 
explanation: the average of 65% and 85% is 75%. how the new group value is distributed to the single lights depends on the values they had before. (in our exampe: light1 got +15% and light1 got +10%)

3. now let's again change group level:
- group slider 100%
--> result for single lights:
- light1: 100%
- light2: 100%
explanation: average of 100% and 100% is 100% (surprise)

from this point on all light changes are distributed uniformly to the single lights. The big advantage is, that all light levels are changed smoothly, when the group level is changed and there are no abrupt changes in the value.

2)
when at least one light of a group is on, you cannot turn on the whole group with a single tap.  In this case the state of the on/off switch in the app is "on" and you have to turn it "off" first and then turn it "on" again.

If I had the choice, I would prefer the behavior of the official hue app, but that's just my personal opinion and I see also the drawbacks.

**Comment by Zefau** [comment]
I thought this through again the last days and I tend to not change anything.
1. The implementation effort is quite high and would mean to break the behavior sending the command to the group but instead sending it to each light of the group in relation to its current state. This could lead to a delay between the lamps when setting a group.
2. The major reason though is that whenever this weird Hue Bridge behavior pointed out in this issue is changed, the whole effort is for nothing and has to be re-implemented.

What do you think?

**Comment by Zefau** [comment]
@daniel1v

**Comment by daniel1v** [comment]
@Zefau , sorry for the late reply. Your points sound reasonable and it maybe wouldn't worth the effort. After thinking about the whole thing again, I also came to the conclusion, that maybe a widget or an additional javascript would be a better place for such a functionality and not the adapter itself. 

So thank you for your effort so far. I will try to test your newest version next weekend, if I have enough time.
