### ISSUE TITLE
Befehlsketten werden nicht korrekt übertragen.

### ISSUE THREAD

**Issue by dercaptainbc** [Zefau/ioBroker.hue-extended#2]
Es treten Probleme auf wenn ich in meinem Script Befehlsketten (wie unten Beschrieben) senden möchte. Die Lampen schalten sich ein und werden auch Langsam heller. Leider aber nur bis alle Lampen 5-6% erreicht haben. Dabei ist es egal welche Zeit ich einstelle. Wenn ich den Befehl direkt über den Browser, über die API, zur Bridge schicke klappt alles ohne Probleme. So das ich vermute das der Fehler hier im Adapter liegen muss.

`setState("hue-extended.0.groups.014-wohnzimmer.action._commands",'{"on":true,"bri":127,"ct":370,"transitiontime":3000}');`

**Comment by Zefau** [comment]
Could you change the instance to `debug` (via instances -> expert mode) and provide the log when applying the action?

**Comment by Zefau** [comment]
Sorry, macht der Gewohnheit. Nochmal auf Deutsch: Bitte die Instanz auf `debug` stellen (unter Instanzen den Expertenmodus aktivieren und dann umstellen). Dann bitte das Debug-Log hier rein kopieren.

**Comment by dercaptainbc** [comment]
Quelle | Zeit | debug | Meldung
-- | -- | -- | --
hue-extended.0 | 2019-09-26 19:26:44.317 | debug | Updated state lights.006-lichtleiste.action._hex to value 030201 (from 050402).
hue-extended.0 | 2019-09-26 19:26:44.317 | debug | Updated state lights.006-lichtleiste.action._cmyk to value 0,33,67,99 (from 0,20,60,98).
hue-extended.0 | 2019-09-26 19:26:44.317 | debug | Updated state lights.006-lichtleiste.action._rgb to value 3,2,1 (from 5,4,2).
hue-extended.0 | 2019-09-26 19:26:44.317 | debug | Updated state lights.006-lichtleiste.action._hsv to value 46,57,1 (from 46,57,2).
hue-extended.0 | 2019-09-26 19:26:44.317 | debug | Updated state lights.006-lichtleiste.action.level to value 1 (from 2).
hue-extended.0 | 2019-09-26 19:26:44.316 | debug | Updated state lights.006-lichtleiste.action.bri to value 1 (from 4).
hue-extended.0 | 2019-09-26 19:25:42.703 | debug | Updated state lights.006-lichtleiste.action._hex to value 050402 (from 0A0904).
hue-extended.0 | 2019-09-26 19:25:42.703 | debug | Updated state lights.006-lichtleiste.action._cmyk to value 0,20,60,98 (from 0,10,60,96).
hue-extended.0 | 2019-09-26 19:25:42.703 | debug | Updated state lights.006-lichtleiste.action._rgb to value 5,4,2 (from 10,9,4).
hue-extended.0 | 2019-09-26 19:25:42.703 | debug | Updated state lights.006-lichtleiste.action._hsv to value 46,57,2 (from 46,57,4).
hue-extended.0 | 2019-09-26 19:25:42.703 | debug | Updated state lights.006-lichtleiste.action.level to value 2 (from 4).
hue-extended.0 | 2019-09-26 19:25:42.702 | debug | Updated state lights.006-lichtleiste.action.bri to value 4 (from 9).
hue-extended.0 | 2019-09-26 19:24:10.798 | debug | Updated state lights.006-lichtleiste.action._hex to value 0A0904 (from 0D0B05).
hue-extended.0 | 2019-09-26 19:24:10.798 | debug | Updated state lights.006-lichtleiste.action._cmyk to value 0,10,60,96 (from 0,15,62,95).
hue-extended.0 | 2019-09-26 19:24:10.798 | debug | Updated state lights.006-lichtleiste.action._rgb to value 10,9,4 (from 13,11,5).
hue-extended.0 | 2019-09-26 19:24:10.798 | debug | Updated state lights.006-lichtleiste.action._hsv to value 46,57,4 (from 46,57,5).
hue-extended.0 | 2019-09-26 19:24:10.798 | debug | Updated state lights.006-lichtleiste.action.level to value 4 (from 5).
hue-extended.0 | 2019-09-26 19:24:10.798 | debug | Updated state lights.006-lichtleiste.action.bri to value 9 (from 12).
hue-extended.0 | 2019-09-26 19:23:09.544 | debug | Updated state lights.006-lichtleiste.action._hex to value 0D0B05 (from 0F0D07).
hue-extended.0 | 2019-09-26 19:23:09.544 | debug | Updated state lights.006-lichtleiste.action._cmyk to value 0,15,62,95 (from 0,13,53,94).
hue-extended.0 | 2019-09-26 19:23:09.544 | debug | Updated state lights.006-lichtleiste.action._rgb to value 13,11,5 (from 15,13,7).
hue-extended.0 | 2019-09-26 19:23:09.544 | debug | Updated state lights.006-lichtleiste.action._hsv to value 46,57,5 (from 46,57,6).
hue-extended.0 | 2019-09-26 19:23:09.543 | debug | Updated state lights.006-lichtleiste.action.level to value 5 (from 6).
hue-extended.0 | 2019-09-26 19:23:09.543 | debug | Updated state lights.006-lichtleiste.action.bri to value 12 (from 14).
hue-extended.0 | 2019-09-26 19:22:38.847 | debug | Updated state groups.015-wolken.action.xy to value 0.4594,0.4104 (from 0.4596,0.4105).
hue-extended.0 | 2019-09-26 19:22:38.847 | debug | Updated state lights.014-wolke_rechts.action.xy to value 0.4594,0.4104 (from 0.4596,0.4105).
hue-extended.0 | 2019-09-26 19:22:38.847 | debug | Updated state lights.006-lichtleiste.action._hex to value 0F0D07 (from 030201).
hue-extended.0 | 2019-09-26 19:22:38.846 | debug | Updated state lights.006-lichtleiste.action._cmyk to value 0,13,53,94 (from 0,33,67,99).
hue-extended.0 | 2019-09-26 19:22:38.846 | debug | Updated state lights.006-lichtleiste.action._rgb to value 15,13,7 (from 3,2,1).
hue-extended.0 | 2019-09-26 19:22:38.844 | debug | Updated state lights.006-lichtleiste.action._hsv to value 46,57,6 (from 46,57,1).
hue-extended.0 | 2019-09-26 19:22:38.844 | debug | Updated state lights.006-lichtleiste.action.level to value 6 (from 1).
hue-extended.0 | 2019-09-26 19:22:38.844 | debug | Updated state lights.006-lichtleiste.action.xy to value 0.4594,0.4104 (from 0.4596,0.4105).
hue-extended.0 | 2019-09-26 19:22:38.843 | debug | Updated state lights.006-lichtleiste.action.bri to value 14 (from 1).
hue-extended.0 | 2019-09-26 19:22:08.180 | debug | Updated state groups.010-kinderzimmer.action.xy to value 0.4594,0.4104 (from 0.4596,0.4105).
hue-extended.0 | 2019-09-26 19:22:08.180 | debug | Updated state lights.017-wolke_links.action.xy to value 0.4594,0.4104 (from 0.4596,0.4105).
hue-extended.0 | 2019-09-26 19:21:37.530 | debug | Updated state groups.015-wolken.action.xy to value 0.4596,0.4105 (from 0.4594,0.4104).
hue-extended.0 | 2019-09-26 19:21:37.530 | debug | Updated state groups.015-wolken.action.on to value true (from false).
hue-extended.0 | 2019-09-26 19:21:37.530 | debug | Updated state groups.015-wolken.state.any_on to value true (from false).
hue-extended.0 | 2019-09-26 19:21:37.530 | debug | Updated state groups.015-wolken.state.all_on to value true (from false).
hue-extended.0 | 2019-09-26 19:21:37.530 | debug | Updated state groups.010-kinderzimmer.action.xy to value 0.4596,0.4105 (from 0.4594,0.4104).
hue-extended.0 | 2019-09-26 19:21:37.530 | debug | Updated state groups.010-kinderzimmer.action.on to value true (from false).
hue-extended.0 | 2019-09-26 19:21:37.530 | debug | Updated state groups.010-kinderzimmer.state.any_on to value true (from false).
hue-extended.0 | 2019-09-26 19:21:37.530 | debug | Updated state groups.010-kinderzimmer.state.all_on to value true (from false).
hue-extended.0 | 2019-09-26 19:21:37.530 | debug | Updated state lights.017-wolke_links.action.xy to value 0.4596,0.4105 (from 0.4594,0.4104).
hue-extended.0 | 2019-09-26 19:21:37.530 | debug | Updated state lights.017-wolke_links.action.on to value true (from false).
hue-extended.0 | 2019-09-26 19:21:37.529 | debug | Updated state lights.014-wolke_rechts.action.xy to value 0.4596,0.4105 (from 0.4594,0.4104).
hue-extended.0 | 2019-09-26 19:21:37.529 | debug | Updated state lights.014-wolke_rechts.action.on to value true (from false).
hue-extended.0 | 2019-09-26 19:21:37.529 | debug | Updated state lights.006-lichtleiste.action._hex to value 030201 (from FFDD6E).
hue-extended.0 | 2019-09-26 19:21:37.529 | debug | Updated state lights.006-lichtleiste.action._xyz to value 0,0,0 (from 70,74,25).
hue-extended.0 | 2019-09-26 19:21:37.529 | debug | Updated state lights.006-lichtleiste.action._cmyk to value 0,33,67,99 (from 0,13,57,0).
hue-extended.0 | 2019-09-26 19:21:37.529 | debug | Updated state lights.006-lichtleiste.action._rgb to value 3,2,1 (from 255,221,110).
hue-extended.0 | 2019-09-26 19:21:37.529 | debug | Updated state lights.006-lichtleiste.action._hsv to value 46,57,1 (from 46,57,100).
hue-extended.0 | 2019-09-26 19:21:37.529 | debug | Updated state lights.006-lichtleiste.action.level to value 1 (from 100).
hue-extended.0 | 2019-09-26 19:21:37.529 | debug | Updated state lights.006-lichtleiste.action.xy to value 0.4596,0.4105 (from 0.4594,0.4104).
hue-extended.0 | 2019-09-26 19:21:37.529 | debug | Updated state lights.006-lichtleiste.action.bri to value 1 (from 254).
hue-extended.0 | 2019-09-26 19:21:37.528 | debug | Updated state lights.006-lichtleiste.action.on to value true (from false).
hue-extended.0 | 2019-09-26 19:21:16.333 | info | Successfully set /groups/10/action/ct on Kinderzimmer (to 370).
hue-extended.0 | 2019-09-26 19:21:16.333 | info | Successfully set /groups/10/action/bri on Kinderzimmer (to 1).
hue-extended.0 | 2019-09-26 19:21:16.333 | info | Successfully set /groups/10/action/on on Kinderzimmer (to true).
hue-extended.0 | 2019-09-26 19:21:16.333 | info | Successfully set /groups/10/action/transitiontime on Kinderzimmer (to 3000).
hue-extended.0 | 2019-09-26 19:21:16.333 | debug | Updated state info.lastAction.lastResult to value [{"success":{"/groups/10/action/transitiontime":3000}},{"success":{"/groups/10/action/on":true}},{"success":{"/groups/10/action/bri":1}},{"success":{"
hue-extended.0 | 2019-09-26 19:21:16.332 | debug | Updated state info.lastAction.lastCommand to value {"on":true,"bri":1,"ct":370,"transitiontime":3000} (from {"on":false,"transitiontime":100}).
hue-extended.0 | 2019-09-26 19:21:16.256 | debug | Send command to Kinderzimmer (groups/10/action): {"on":true,"bri":1,"ct":370,"transitiontime":3000}.
hue-extended.0 | 2019-09-26 19:21:15.767 | debug | Add to queue ({"path":"groups.010-kinderzimmer.action","type":"groups","deviceId":"010-kinderzimmer","name":"Kinderzimmer","uid":"10","trigger":"groups/10/action"}) commands: {"on":true,"bri":1,"ct":3
hue-extended.0 | 2019-09-26 19:21:15.767 | debug | Updated state hue-extended.0.groups.010-kinderzimmer.action._commands to value (from undefined).
hue-extended.0 | 2019-09-26 19:21:15.765 | debug | State of hue-extended.0.groups.010-kinderzimmer.action._commands has changed {"val":"{\"on\":true,\"bri\":127,\"ct\":370,\"transitiontime\":3000}","ack":false,"ts":1569518475739,"q":0,"from":"system.



Das Beispiel wäre jetzt nicht das Wohn- sondern Kinderzimmer. Aber das sollte ja egal sein. Liegt es vielleicht an den Schrägstrichen? 

`kinderzimmer.action._commands has changed {"val":"{\"on\":true,\"bri\":127,\"ct\":370,\"transitiontime\":3000}","ack":false,"ts":1569518475739,"q":0,"from":"system.`

**Comment by Zefau** [comment]
Ok, Danke. Glaube ich hab den Fehler gefunden. Kannst du die Github Version mal installieren und probieren? Die Versionsnummer bleibt gleich.

**Comment by dercaptainbc** [comment]
Vielen Herzlichen Dank. Jetzt funktioniert alles wie gewünscht.
