### ISSUE TITLE
Hue dimmer switch: offline after battery change

### ISSUE THREAD

**Issue by Maschler** [Zefau/ioBroker.hue-extended#28]
Hello everybody,
Thank you for a great job.

I am currently connecting my Hue dimmer switch. I have noticed one problems:

When I change the battery on a dimmer switch, the switch no longer works with the new battery. Only after I reconnect the switch will it work again. With the original Hue Bridge the switch still works after changing the battery.

**Comment by Zefau** [comment]
Did it solve itself or why did you close it?

**Comment by Maschler** [comment]
hi,
that was a little awkward. I had several tabs open in firefox and accidentally posted this issue in your github project. I didn't realize it was the wrong tab...
