### ISSUE TITLE
Hue dimmer switch: Click Count is missing 

### ISSUE THREAD

**Issue by Maschler** [Zefau/ioBroker.hue-extended#29]
Hello,

I noticed a second thing. The click count, which is enumerated by the Hue dimmer switch (on/off, brightness, up/down/hold/release, **click count)** is also not existing for the objects. 

<img width="690" alt="Unbenannt" src="https://user-images.githubusercontent.com/38862834/72560334-22a2a600-38a7-11ea-9b0e-c9fb765462e5.PNG">

thx

**Comment by Zefau** [comment]
Did it solve itself or why did you close it?

**Comment by Maschler** [comment]
hi,
that was a little awkward. I had several tabs open in firefox and accidentally posted this issue in your github project. I didn't realize it was the wrong tab...
