### ISSUE TITLE
Helligkeit / Level / State auf 0 setzen wenn nicht erreichbar

### ISSUE THREAD

**Issue by m-s-b** [Zefau/ioBroker.hue-extended#38]
Ich hätte gerne analog zu
"Setze Helligkeit auf 0, wenn das Gerät ausgeschaltet wird"
in der "Weiteren Einstellungen" des Adapters eine neue Option, sinngemäß
"Setzte Helligkeit / Level / State auf 0, wenn das Gerät nicht erreichbar ist."
Bei Lampen und Steckdosen die physisch vom Strom getrennt werden ist das ganz nützlich. 
Evtl. kann man das ja sogar pro Lampe / Gerät selektieren.

**Comment by Zefau** [comment]
@m-s-b Habe dir die Option hinzugefügt. Könntest du das bitte testen? Ich habe aktuell kein Gerät, dass nicht erreichbar wäre, daher kann ich es nicht testen.

**Comment by m-s-b** [comment]
@Zefau 
Test abgeschlossen. Für einzelne Lampen funktioniert es fast perfekt. Das Level wird auf 0% gesetzt, der Datenpunkt "on" bleibt aber true.
Wenn ich eine Gruppe aus zwei Lampen habe werden die einzelnen Lampen wie gewünscht auf 0% gesetzt, die Gruppe bleibt leider auf dem alten Wert stehen. Kannst du noch einbauen, dass die Gruppe auch auf 0% gesetzt wird wenn die enthaltenen Lampen auf 0% gesetzt werden?
Evtl. löst sich das ja von alleine, wenn bei nicht erreichbar auch "on" auf false gesetzt wird.
Danke schonmal!

**Comment by Zefau** [comment]
@m-s-b bzgl. der Gruppe setze ich dann `reachable`, `on` auf `false` bzw. `level` auf 0, wenn **alle** Lichter nicht erreichbar sind, korrekt? Also sobald auch nur ein Licht erreichbar ist, bleibt auch die Gruppe auf reachable?

**Comment by Zefau** [comment]
@m-s-b bitte `v1.3.3` probieren. Dort gibt es nun einen `reachable` state für Gruppen basierend auf den Lichtern. Wenn alle Lichter nicht erreichbar sind, wird die Gruppe als nicht erreichbar entsprechend gekenntzeichnet.

**Comment by m-s-b** [comment]
@Zefau 
v1.3.3 installiert, upload und reboot durchgeführt. In der Gruppe kein reachable state und all_on, any_on, on auf true obwohl keine Lampe der Gruppe erreichbar ist. 
Level bleibt auch auf den 50% stehen.

**Comment by Zefau** [comment]
@m-s-b Kannst du nochmal die neue Version 1.3.4 probieren? Hiermit sollte nun der reachable state auf der Gruppe erstellt werden und brightness auf 0 gehen.

**Comment by Zefau** [comment]
@m-s-b

**Comment by m-s-b** [comment]
@Zefau 
Sorry, die Benachrichtigung ist untergegangen....
Hab jetzt die 1.3.5 installiert und getestet. Wird die Gruppe per Lichtschalter vom Strom genommen werden die einzelnen Lampen auf level "0%" und on auf "false" gesetzt. Die Gruppe wird auf on "false" gesetzt, der Wert Level bleibt weiter auf dem letzten Wert. all_on und any_on bleiben auf "true", rechable geht auf "false"

**Comment by Zefau** [comment]
Also zusammengefasst:
- einzelne Lampen: `level` und `on` sind korrekt
- Gruppe: `on` ist korrekt; `level`, `all_on` und `any_on` **inkorrekt**
- `reachable` ist korrekt

richtig?

**Comment by m-s-b** [comment]
Genau so ist es bei mir. Upload , reboot etc. probiert...

**Comment by Zefau** [comment]
`all_on` und `any_on` sind auch bei mir falsch, die hab ich vergessen. `level` muss ich nochmal forschen, woran das liegen könnte.
Kannst du mir durchgeben, wie die anderen Adapter-Einstellungen gesetzt sind? Ggf. wird es durch eine andere Einstellung überschrieben.

**Comment by m-s-b** [comment]
![20200525_205929](https://user-images.githubusercontent.com/46641961/82837982-fd641b00-9eca-11ea-8495-7eef0bb0ec51.jpg)
Reicht das oder mehr? Sorry, gerade kein PC in Reichweite.

**Comment by Zefau** [comment]
Jo passt, danke.

**Comment by Zefau** [comment]
Kannst du nochmal die aktuelle Version von Github (Versionsnummer bleibt bei 1.3.5) drüber installieren und prüfen, ob es nun funktioniert? Habe es nun selbst (grob) testen können und bei mir sieht es soweit gut aus.

**Comment by m-s-b** [comment]
Hab es gerade mal fix getestet, schaut gut aus.  Danke!
Lasse dann mal wieder Virtual Power Meter drauf los... Sollte im Dauerbetrieb was klemmen melde ich mich wieder.

**Comment by Zefau** [comment]
Kann ich das Issue dann schließen oder willst du den Test des Dauerbetriebs noch abwarten?
Was ist Virtual Power Meter überhaupt? :)

**Comment by m-s-b** [comment]
Ja, ist für mich durch ;-)
Bei Geräten die keine Verbrauchswerte liefern, aber on/off oder % kann man den Nennverbrauch hinterlegen und hat dann nen angenäherten  Verbrauchsverlauf.
