### ISSUE TITLE
dim function as in the hue app

### ISSUE THREAD

**Issue by dercaptainbc** [Zefau/ioBroker.hue-extended#41]
Is it possible to dim only that lamps in a group which are `on = true` or `brightness >= 0` (like in the Hue App)

**Comment by Zefau** [comment]
Same discussion as https://github.com/Zefau/ioBroker.hue-extended/issues/16.
I think I will add an option for this then.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.hue-extended/commit/bb79b4dc66aff991bc661d2fc23d939a0dc4ebfd

**Comment by Zefau** [comment]
@dercaptainbc please test `v1.3.0` from Github, which provides an option to only set devices which are on already

**Comment by Zefau** [comment]
@daniel1v regarding our discussion in https://github.com/Zefau/ioBroker.hue-extended/issues/16 I have now added an option. Though, it is only very simplified.

**Comment by dercaptainbc** [comment]
Where I can find the option to actived the function or is it "hard coded"?

Anyway it doesnt work for me. And It doesnt matter if I use `_commands`, `brightness` or `level` the lamps which are `off` are also set to the brightness value

**Comment by Zefau** [comment]
If you cant see the option please upload the Adapter, do
```
iobroker upload hue-extended
```

**Comment by daniel1v** [comment]
@Zefau 
for me all tests worked perfectly. thank you for adding this option. this makes the whole thing much more useable for me. :)

**Comment by dercaptainbc** [comment]
Unfortunately, it doesn't work for me at all. When I change the DP 'on' or 'level' I can see in the log that the command arrives but the lamps in the groups are not switched. Single Lamps can be switched.

I already tried with upload command.

**Comment by Zefau** [comment]
Delete the states and restart the adapter. Does that help?

**Comment by Zefau** [comment]
@dercaptainbc have you had the chance to delete the states, restart the adapter and test again?

If not, please set the instance to `debug` and provide the log when setting a lamp. Thanks!

**Comment by Zefau** [comment]
@dercaptainbc

**Comment by dercaptainbc** [comment]
Hi @Zefau sorry for the delay I'll test it today. I'll give my feedback tomorrow.

**Comment by dercaptainbc** [comment]
Also was gut funktioniert ist das nur die Lampen gesteuert werden die in der jeweiligen auch eingeschaltet sind. Aber sobald in der Gruppe alle Lampen aus sind kann ich die ganze Gruppe nicht auf einmal einschalten. Ich muss erst jede einzelne Lampe einschalten.

**Comment by Zefau** [comment]
@dercaptainbc Kannst du nochmal die neue Version 1.3.4 von Github probieren, ob es damit geht?

**Comment by Zefau** [comment]
@dercaptainbc

**Comment by Zefau** [comment]
@dercaptainbc
