### ISSUE TITLE
Scenes: Action: on switch behaves like a toggle switch

### ISSUE THREAD

**Issue by culpinnis** [Zefau/ioBroker.hue-extended#42]
Hi there, 

When I use the on-action for scenes it behaves like a toggle switch. So when the current setting is true and I write true again to the on-action, the scene is set to false (and vice versa). 
Maybe this is a wanted behaviour, but for me, it was a bit unexpected.
It makes the use in a script (or an iobroker-scene) a bit more complicated because one always has to check the current state.

I don't know if it is important, but I use it on HueLabScenes. 

Best wishes
Chris

**Comment by Zefau** [comment]
Thanks for reporting, I will have a look at this.

**Comment by Zefau** [comment]
I had a look and can confirm the bug. I will provide a fix soon.

**Comment by Zefau** [comment]
Could you try v1.3.0, which addresses a fix for this? Thanks

**Comment by culpinnis** [comment]
Thanks for the fast fix. I will try it and provide feedback asap.

**Comment by culpinnis** [comment]
Seems to work as supposed! 
Thanks!
