### ISSUE TITLE
lots of datapoints are deleted over the night

### ISSUE THREAD

**Issue by dercaptainbc** [Zefau/ioBroker.hue-extended#44]
I do not know exactly whether this adapter is faulty, but I always have the problem that many data points are deleted from one day to the next. Basically only 'brightness', 'on', 'transitiontime' and 'xy' remain. Furthermore, almost all lights / groups are deleted. 

I suspected the garbage collector, but I can't say it finally. Maybe you have a clue what you can check. 

It's the second time that I have this issue, I'll deactived the garbage collector temporally. But the issue happen very rarely so I can not say when I can report something new.

Unfortunately I didn't find anything in the log.

**Comment by dercaptainbc** [comment]
I've anyone else get the same issue : restarting the instance recreated all missing datapoints.

**Comment by Zefau** [comment]
Sounds like the garbageCollector. It runs every hour and deletes states which have not been updated within 24 hours.
Do you have a refresh time set (`Intervall zur Aktualisierung aller Einstellungen / Daten (in Sekunden). Wenn auf 0 gesetzt werden die Einstellungen nur beim Adapter-Start aktualisiert.`) ?  This should actually update all states regularly.

**Comment by dercaptainbc** [comment]
Yes, its set to `2` at the moment

**Comment by Zefau** [comment]
@dercaptainbc did this happen again so far?

**Comment by dercaptainbc** [comment]
no not so far. In the whole time I've used your adapter it only happens 2 times.

**Comment by Zefau** [comment]
Let me closed this for now then hoping it has been resolved properly. If it happens again, we will reopen the ticket.
