### ISSUE TITLE
Adapter gelb nach Stromunterbrechung Hue Bridge

### ISSUE THREAD

**Issue by bergjet** [Zefau/ioBroker.hue-extended#58]
V1.3.2
Nach einer Stromunterbrechung der Hue Bridge geht der Adapter nicht mehr auf grün. Erst nach Neustart des Adapters.

**Comment by Zefau** [comment]
Eigl. ist das Verhalten gewollt. Wenn der Adapter keine Daten aufrufen kann, dann versucht er es 10x erneut in einem Abstand von 10 Sekunden. Nach dem 11x wird er gelb und geht quasi aus, damit nicht ständig gepollt wird.

Nach deiner Beschreibung kann ich aber nachvollziehen, dass das nicht unbedingt die beste Lösung ist.

Insofern werde ich nach den 10 Sekunden einfach den Polling-Abstand auf eine Minute erhöhen und so lange pollen, bis wieder eine Verbindung besteht.

**Comment by Zefau** [comment]
@bergjet bitte 1.3.6 direkt von Github installieren und prüfen, ob es damit behoben ist. Danke!

**Comment by Zefau** [comment]
@bergjet bitte 1.3.6 direkt von Github installieren und prüfen, ob es damit behoben ist. Danke!

**Comment by bergjet** [comment]
Nein, gleich wie davor. Adapter bleibt gelb bis zum händischen Neustart.

**Comment by Zefau** [comment]
Könntest du bitte 1.3.7 probieren, ob es nun damit geht? Danke dir

**Comment by bergjet** [comment]
Keine Änderung.

**Comment by Zefau** [comment]
Dann weiß ich nicht genau, woran es liegt. Kannst du mir sagen, was im Log steht?

Wenn der Adapter keine Verbindung hat, sollte der Fehler erscheinen `Error while retrieving payload from Hue Bridge`.
Darauf sollte `Error connecting to Hue Bridge` kommen inkl. der Anzahl der fehlgeschlagenen Versuche.

Der Adapter versucht 10x alle 10 Sekunden und danach jede Minute neu zu verbinden.
Kannst du mir das Log schicken ?

**Comment by Zefau** [comment]
Danke dir für die Logs. Sieht für mich so aus, als wäre der Adapter wieder verbunden, aber die Ampel bleibt einfach gelb und geht nicht mehr auf grün.

Ich hab's mit 1.3.8 nun hoffentlich hinbekommen. Kannst du es nochmal probieren und von Github installieren? Danke dir

**Comment by bergjet** [comment]
Jetzt gehts mit der 1.3.8
Danke
