### ISSUE TITLE
Hue motion sensor, Schaltdauer

### ISSUE THREAD

**Issue by coldfusion75** [Zefau/ioBroker.hue-extended#59]
Hi Zefau,

zu allererst vielen Dank für den hue-extended, wie aber auch deine anderen Adapter, klasse Arbeit!!!
Folgendes Problem: Ich schalte via blockly Skript eine Lampe bei Bewegungsauslösung eines Hue motion Sensors, das funktioniert auch alles prima, jedoch schaltet der Sensor die Lampe immer schon sehr schnell/nach wenigen Sekunden wieder aus.
Gibt es da in deinem Adapter ein Objekt, dass ich mit einem anderen Wert belegen, so dass ich selbst entscheiden kann, wann der Sensor quasi die Lampe wieder ausschaltet?

Vielen Dank soweit und beste Grüsse
coldfusion75

**Comment by Zefau** [comment]
Der Adapter lädt alle Werte der API in die Objekte. Also alles, was im Objekt-Baum vorhanden ist, ist quasi 100%. Da ich keinen Hue Motion Sensor habe, kenne ich die Objekte / States nicht.

Deine Beschreibung klingt aber so, als könnte es durch Programmierung gelöst werden, sofern ich es richtig verstehe.
Du willst, dass bei Bewegungsauslösung die Lampe anschaltet und dann sicherlich nach einer bestimmten Zeitdauer wieder abschaltet? Insofern einfach das Skript so umstellen, dass er bei Auslösung (`true`) schaltet, aber beim zurückspringen (`false`) nichts macht. Stattdessen die Lampe nach einem Timeout wieder ausschalten.

Im Javascrip

**Comment by Zefau** [comment]
Beispielsweise:
```js
let motionSensorId = 'HIER DIE IOBROKER OBJEKT ID DES SENSORS';
let lightId = 'HIER DIE IOBROKER OBJEKT ID DER LAMPE';

on({ 'id': motionSensorId, 'val': true }, state => {
	
	setState(lightId , true)
	setTimeout(() => setState(lightId , false), 60*1000); // wieder aus nach 60s
});
```

**Comment by coldfusion75** [comment]
Hi Zefau,

ja, ich habe es jetzt so direkt im Skript gelöst. Dachte die hue-Objekte tholddark bzw. tholdoffset könnten damit etwas zu tun haben...

Danke und Grüsse
coldfusion75
