### ISSUE TITLE
Error connecting to Hue Bridge: Error: connect ENETUNREACH

### ISSUE THREAD

**Issue by Bibo13** [Zefau/ioBroker.hue-extended#63]
Hallo Zefau,
nach umstieg auf 1.3.8 habe ich alle 10 min diese Meldung:
Error connecting to Hue Bridge: Error: connect ENETUNREACH

Gibt es da ein Problem mit dem Netzwerk?
Die Geräte lassen sich steuern. Nur diese Meldung kommt jetzt regelmässig.
Gruß

**Comment by Zefau** [comment]
Welche refresh Zeit ist eingestellt? Wenn der Fehler “nur“'alle 10 Minuten kommt, dann scheint die Frequenz zu häufig und ab und an überholt sich die Abfrage dann selbst.

**Comment by Bibo13** [comment]
Das Intervall steht auf 10s.
So steht es eigentlich schon immer ohne Probleme

**Comment by Zefau** [comment]
Der Fehler existierte auch immer schon, wird aber mit der neuen Version erst im Log angezeigt. Ich ändere das wieder zurück, dann wird der Fehler erst angezeigt, wenn er wiederholt auftritt.

**Comment by Bibo13** [comment]
Ok, danke

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.hue-extended/commit/e9367b7416bb404720967db9c70af5ae77932543
