### ISSUE TITLE
Adapter stürzt ab und bleibt rot

### ISSUE THREAD

**Issue by Bibo13** [Zefau/ioBroker.hue-extended#64]
Hallo Zefau,
momentan ist es wie verhext. Das nächste Problem mit dem Adapter.
Ich habe Iobroker schon restartet und mehrmals probiert die Instance neu zu starten.
Hilft alles nichts. 
Ich habe den Adapter auf Debug gestellt und neu gestartet. Das Log hängt mit dran.
Vielleicht kannst Du mir helfen Danke im vorraus.
[Hue-extended.txt](https://github.com/Zefau/ioBroker.hue-extended/files/4944224/Hue-extended.txt)

**Comment by Zefau** [comment]
(Re)Starte den Adapter mal bitte und warte, bis die erste Synchronisierung durchgelaufen ist und der State `hue-extended.0.info.datetime` aktualisiert. Tritt der Fehler dann auch auf?

**Comment by Bibo13** [comment]
Also wenn ich den starte schmiert er ganz schnell ab. Müßte aber auch in dem Log sein.

**Comment by Bibo13** [comment]
host.Elzershark | 2020-07-19 20:43:35.137 | info | Restart adapter system.adapter.hue-extended.0 because enabled
-- | -- | -- | --
host.Elzershark | 2020-07-19 20:43:35.135 | info | instance system.adapter.hue-extended.0 terminated with code 0 (NO_ERROR)
hue-extended.0 | 2020-07-19 20:43:35.003 | warn | (10121) Command can not be send to device due to error (no UID)!
hue-extended.0 | 2020-07-19 20:43:35.002 | debug | (10121) State of hue-extended.0.groups.schlafzimmer-5.action.level has  changed  {"val":0,"ack":false,"ts":1595184214987,"q":0,"from":"system.adapter.javascript.0","user":"system.user.admin","lc":15951
hue-extended.0 | 2020-07-19 20:43:34.798 | warn | (10121) Command can not be send to device due to error (no UID)!
hue-extended.0 | 2020-07-19 20:43:34.797 | debug | (10121) State of hue-extended.0.groups.schlafzimmer-5.action.level has  changed  {"val":0,"ack":false,"ts":1595184214785,"q":0,"from":"system.adapter.javascript.0","user":"system.user.admin","lc":15951
hue-extended.0 | 2020-07-19 20:43:34.667 | warn | (10121) Command can not be send to device due to error (no UID)!
hue-extended.0 | 2020-07-19 20:43:34.651 | debug | (10121) State of hue-extended.0.groups.schlafzimmer-5.action.level has  changed  {"val":0,"ack":false,"ts":1595184214584,"q":0,"from":"system.adapter.javascript.0","user":"system.user.admin","lc":15951
hue-extended.0 | 2020-07-19 20:43:34.536 | info | (10121) Terminated (NO_ERROR): Without reason
hue-extended.0 | 2020-07-19 20:43:34.531 | info | (10121) terminating
hue-extended.0 | 2020-07-19 20:43:34.517 | warn | (10121) Command can not be send to device due to error (no UID)!
hue-extended.0 | 2020-07-19 20:43:34.517 | debug | (10121) State of hue-extended.0.groups.schlafzimmer-5.action.level has  changed  {"val":0,"ack":false,"ts":1595184214384,"q":0,"from":"system.adapter.javascript.0","user":"system.user.admin","lc":15951
hue-extended.0 | 2020-07-19 20:43:34.516 | warn | (10121) Command can not be send to device due to error (no UID)!
hue-extended.0 | 2020-07-19 20:43:34.516 | debug | (10121) State of hue-extended.0.groups.schlafzimmer-5.action.level has  changed  {"val":0,"ack":false,"ts":1595184214187,"q":0,"from":"system.adapter.javascript.0","user":"system.user.admin","lc":15951
hue-extended.0 | 2020-07-19 20:43:34.515 | warn | (10121) Command can not be send to device due to error (no UID)!
hue-extended.0 | 2020-07-19 20:43:34.513 | debug | (10121) State of hue-extended.0.groups.schlafzimmer-5.action.level has  changed  {"val":0,"ack":false,"ts":1595184213984,"q":0,"from":"system.adapter.javascript.0","user":"system.user.admin","lc":15951
hue-extended.0 | 2020-07-19 20:43:34.511 | info | (10121) Adapter stopped und unloaded.
hue-extended.0 | 2020-07-19 20:43:34.509 | error | at processImmediate (timers.js:658:5)
hue-extended.0 | 2020-07-19 20:43:34.509 | error | at tryOnImmediate (timers.js:676:5)
hue-extended.0 | 2020-07-19 20:43:34.509 | error | at runCallback (timers.js:705:18)
hue-extended.0 | 2020-07-19 20:43:34.509 | error | at Immediate.setImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5388:34)
hue-extended.0 | 2020-07-19 20:43:34.509 | error | at Adapter.emit (events.js:198:13)
hue-extended.0 | 2020-07-19 20:43:34.509 | error | at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.hue-extended/hue-extended.js:311:81)
hue-extended.0 | 2020-07-19 20:43:34.509 | error | (10121) TypeError: Cannot read property '5' of undefined
hue-extended.0 | 2020-07-19 20:43:34.503 | error | (10121) uncaught exception: Cannot read property '5' of undefined
hue-extended.0 | 2020-07-19 20:43:34.499 | debug | (10121) State of hue-extended.0.groups.schlafzimmer-5.action.level has  changed  {"val":0,"ack":false,"ts":1595184213783,"q":0,"from":"system.adapter.javascript.0","user":"system.user.admin","lc":15951
hue-extended.0 | 2020-07-19 20:43:32.353 | info | (10121) Establishing connection to bridge..
hue-extended.0 | 2020-07-19 20:43:32.309 | info | (10121) starting. Version 1.3.8 in /opt/iobroker/node_modules/iobroker.hue-extended, node: v10.20.1, js-controller: 3.1.4

**Comment by Zefau** [comment]
Also laut Log wird der Datenpunkt `hue-extended.0.groups.schlafzimmer-5.action.level` getriggert mit `ack` = `false`. Hast du ein Skript, was den Datenpunkt triggert?
Der Adapter selbst updated nur mit `ack` = `true`, was das obige Log nicht auslösen würde.

**Comment by Zefau** [comment]
Probier sonst mal bitte v2.0.0-rc.3, ob es dort behoben ist.

**Comment by Bibo13** [comment]
Die idee mit dem Skript wahr GOLD wert. Ich habs abgestellt. (ist ein Taster dahinter der irgendwie den ganzen Cache voll gesaut hat)
Der Adapter ist wieder gestartet.
Danke für Deine Bemühungen.
viele Grüße
