### ISSUE TITLE
Light Level is not kept when switching a group off/on

### ISSUE THREAD

**Issue by Line40** [Zefau/ioBroker.hue-extended#7]
With the latest version (1.0.1) the light level is set to 100 when switching on a group, regardless of the level the group had when switching it off.

The issue can be easily reproduced by setting a group to on using `action.on` in the iobroker objects section, then setting the `action.level` to something like 50, then switching the light off and on again.

In the last version I used (0.8.7) the light level was restored.

It would be nice if you could restore this behaviour, it was one of the main reasons I switched to hue-extended in favour of the default hue adapter.

**Comment by Zefau** [comment]
Do you have the option `Set brightness to 0, when device is turned off` (`Setze Helligkeit auf 0, wenn das Gerät ausgeschaltet wird`) activated?

**Comment by Zefau** [comment]
With the option activated `level` will be set `0` and the actual value save in the background.
This is works for me.

If the option is not activated the `level` value will stay unchanged when setting the device `on` or `off`.
In can confirm, that this seems to be buggy. Thanks for reporting.

**Comment by Line40** [comment]
@Zefau It seems the issue only occurs if `Set brightness to 0, when device is turned off` is unchecked. If I check the option, the brightness is saved correctly. Sorry I thought I tried this before reporting, apparently I did something wrong testing. 
The name of the option may be somewhat misleading, I thought when I check it the brightness is reset.

**Comment by Zefau** [comment]
Please check out `v1.1.0`. This should address and fix this issue.

**Comment by Zefau** [comment]
@Line40 have you had the chance to test the fix?

**Comment by Zefau** [comment]
@Line40 have you had the chance to test the fix?

**Comment by Line40** [comment]
@Zefau I tested it during the weekend, everything seems to work now. Thanks for the quick fix :) 

As a side note I had to manually install the adapter, since iobroker doesn't offer the version for automatic upgrade.
