### ISSUE TITLE
Schaltbefehle werden nicht ausgeführt

### ISSUE THREAD

**Issue by QuoxelNet** [Zefau/ioBroker.hue-extended#75]
Hallo zefau,
sorry, ich schon wieder...

Nachdem ich die mehreren Hunderttausend Datenpunkte erfolgreich löschen konnte, habe ich nun das nächste Problem: 
Bei den HUE-Gruppen werden keine Schaltbefehle durchgeführt. Das heisst, man setzt z.B. von einer Gruppe unter action/on den Wert "true" - aber es passiert nichts. Setzt man z.B. den Wert "level" auf einen anderen Wert, ändert sich der Wert vielleicht, aber das Licht passt sich dem neu eingestellten Wert nicht an. Teilweise wird auch wieder der alte Wert eingestellt.

Bei den Lampen oder Szenen kann ich Werte ändern, diese werden auch sofort vom HUE-System übernommen. Die prinzipielle Kommunikation funktioniert also. Aber die Lampengruppen wären natürlich schon sehr hilfreich.
Oder verstehe ich das falsch? Wenn ich z.B. das Licht in einem Raum über eine Schaltfläche der Visualisierung einschalten und/oder dimmen will - über welchen Datenpunkt sollte das idealerweise passieren?

**Comment by Zefau** [comment]
Kannst du den Adapter bitte auf `debug` stellen und das Log des Schaltbefehls bereitstellen? Bitte auch einen Screenshot der Adapter-Konfiguration.

**Comment by QuoxelNet** [comment]
Folgenden Logeintrag gibt es, der aber nicht weiterhilft, befürchte ich...
![grafik](https://user-images.githubusercontent.com/48298760/92034700-e5bfec80-ed6d-11ea-9091-3a31d759155f.png)
Das sind meine Einstellungen:
![grafik](https://user-images.githubusercontent.com/48298760/92034898-35061d00-ed6e-11ea-9f4b-8d143628e6a8.png)

Komisch, dass die direkten Lampenbefehle durchgehen...

**Comment by Zefau** [comment]
Sieht so aus als würde es an der Option `Nur angeschaltet Lichter einer Gruppe schalten`. Ich versuche es mal zu fixen. Gerne kannst du in der Zwischenzeit mal schauen, ob es ohne dieser Option geht?

**Comment by Zefau** [comment]
@QuoxelNet Sollte mit `v2.0.1` behoben sein.

**Comment by QuoxelNet** [comment]
Hu, da warst du zu schnell ;) Aber ich habe es trotzdem mal mit ausgeschalteter Option getestet - da gehts. Das Update wird mir noch nicht angezeigt, sobald ich es installiert habe, teste ich noch mal und berichte umgehend!
Vielen Dank für die schnelle Behebung!

**Comment by Zefau** [comment]
Das Update bitte von Github installieren. Bevor es ins latest geht möchte ich sicher sein, dass es behoben ist.

**Comment by QuoxelNet** [comment]
Habs gerade getestet, es funktioniert! Super, danke dafür!
