### ISSUE TITLE
Sensoren ein-/ausschalten

### ISSUE THREAD

**Issue by darkman242** [Zefau/ioBroker.hue-extended#77]
Hallo,
ich möchte gerne über den Objekt-Baum einen Motion-Sensor ein-/ausschalten. Eine Änderung des State: On wirkt sich nicht aus. Im Debug-Log des Adapters (Version: 2.0.0 ist installiert) wird keine Meldung ausgegeben.

Was mache ich falsch?

![image](https://user-images.githubusercontent.com/46793576/92924497-57b4c780-f439-11ea-92be-8450db12395d.png)

**Comment by Zefau** [comment]
Was steht im Log, wenn die Instanz auf `debug` gesetzt ist?

**Comment by darkman242** [comment]
Im Log wird erstaunlicherweise gar nichts geloggt wenn ich den State ändere. Ein-/Ausschalten eines Strahlers wird korrekt geloggt. Hängt es evtl damit zusammen, dass ich den Sensor in der Hue-App umbenannt habe. Ein Schalten in meiner ioBroker-Dev-Umgebung über den Hue-Adapter funktioniert einwandfrei.

**Comment by Zefau** [comment]
Kannst du mir bitte deine Konfiguration als Screenshot posten, ähnlich wie in https://github.com/Zefau/ioBroker.hue-extended/issues/75 ?

**Comment by Zefau** [comment]
Von was in was hast du denn umbenannt? Und wie das umbenannte Gerät auch in den Objekten angezeigt?

**Comment by darkman242** [comment]
![image](https://user-images.githubusercontent.com/46793576/93120232-572f6180-f6c3-11ea-91cf-f1d6f4fcdfda.png)

![image](https://user-images.githubusercontent.com/46793576/93120350-85ad3c80-f6c3-11ea-8db4-02394292e47b.png)

Umbenannte hatte ich den Hue Outdoor Motion Sensor in Whirlpool. Den Licht-/Temperatursensor-Teil hat er aber nicht umbenannt in den Objekten.

**Comment by Zefau** [comment]
Seltsam. Auch, dass die IDs (3+4 vs. 2) ja anders sind. Werden die Timestamps aktualisiert?

**Comment by darkman242** [comment]
![image](https://user-images.githubusercontent.com/46793576/93123034-c73fe680-f6c7-11ea-84bb-315401c3cc56.png)

Timestamps werden aktualisiert. Der Hue-Adapter liefert die 3 Teile des Gerätes mit den selben Namen zurück.

**Comment by Zefau** [comment]
Sollte mit `v2.0.1` behoben sein.

**Comment by darkman242** [comment]
Funktioniert jetzt mit dem State wie gewünscht - Sensor lässt sich ein- und ausschalten. Danke
