### ISSUE TITLE
Issue with "transitiontime"

### ISSUE THREAD

**Issue by dercaptainbc** [Zefau/ioBroker.hue-extended#8]
Hey, I've updated the adapter manulley to version 1.1.0 and unfortunately I realized that something goes wrong with transition time value. But its a little bit strange because, I've a script that changed color from green to blue with an 50 (5s) transition time. The initial color change works fine, but the second and third color change switched directly to the new color without any delay.

After downgrade to 1.0.2. (version that I had before) everthing works fine.

this time in english, so that you don't need to write a new comment ;-P

**Comment by dercaptainbc** [comment]
In the meantime I've changed the adapter into debug mode and found out the following thing.. 

*inital color change*
`hue-extended.0	2019-10-27 22:34:56.909	info	(460) Attempt 1x - Successfully set Hue play Rechts.
hue-extended.0	2019-10-27 22:34:56.908	debug	(460) Successfully set /lights/24/state/sat on Hue play Rechts (to 132).
hue-extended.0	2019-10-27 22:34:56.906	debug	(460) Successfully set /lights/24/state/hue on Hue play Rechts (to 28945).
hue-extended.0	2019-10-27 22:34:56.904	debug	(460) Successfully set /lights/24/state/transitiontime on Hue play Rechts (to 50).
hue-extended.0	2019-10-27 22:34:56.870	debug	(460) Attempt 1x - Send commands to Balkon (lights/23/state): {"hue":40595,"sat":196,"transitiontime":50}.`

*all other color changes*
`hue-extended.0	2019-10-27 22:35:03.041	info	(460) Attempt 1x - Successfully set Hue play Rechts.
hue-extended.0	2019-10-27 22:35:03.039	debug	(460) Successfully set /lights/24/state/sat on Hue play Rechts (to 196).
hue-extended.0	2019-10-27 22:35:03.037	debug	(460) Successfully set /lights/24/state/hue on Hue play Rechts (to 40595).
hue-extended.0	2019-10-27 22:35:03.004	debug	(460) Attempt 1x - Send commands to Balkon (lights/23/state): {"hue":28945,"sat":132}.`

**Comment by dercaptainbc** [comment]
*any color change with version 1.0.2 

```
(12372) Successfully set Hue play Rechts.
(12372) Successfully set /lights/24/state/sat on Hue play Rechts (to 196).
(12372) Successfully set /lights/24/state/hue on Hue play Rechts (to 40595).
(12372) Successfully set /lights/24/state/on on Hue play Rechts (to true).
(12372) Successfully set /lights/24/state/transitiontime on Hue play Rechts (to 50).
```

**Comment by Zefau** [comment]
I can confirm this will fix it tomorrow. This is because I added a function to verify if the command that is sent is actually different from current state (so no unnecessary commands are sent). I add an exception for transitiontime.

**Comment by Zefau** [comment]
Could you test and verify this issue with v1.1.2 (available on Github). Thanks

**Comment by Zefau** [comment]
Now available on npm as well

**Comment by dercaptainbc** [comment]
looks fine so far for me. Thanks a lot for the quick solution of the problem!
