### ISSUE TITLE
switch hueLabsScenes

### ISSUE THREAD

**Issue by mcbirne** [Zefau/ioBroker.hue-extended#80]
If I change the state in a HueLabsScene nothing happens. I thourd if I change the action/lastAction/on state to true or false is should switch the light on or of. But nothing happens.
If I activate the scene in the hue app this state changes automatically.

**Comment by mcbirne** [comment]
So wie es aussie geht es hier auch in Deutsch. 
Ich habe hier noch etwas herumprobiert und festgestellt, dass der Hue-extended Adapter die Werte für das aktivieren einer HueLabsScenes wohl nicht auf die Hue Bridge schreibt. Daher ist es vielleicht auch ein Featurewunsch. Ist diese Funktionalität vorgesehen?

**Comment by Zefau** [comment]
Welche Wert werden nicht auf die Bridge geschrieben? 

Die Szene selbst wird - zumindest bei mir - getriggert?

**Comment by Zefau** [comment]
Der Datenpunkt `.action.on` (z. B. hue-extended.0.scenes.HueLabsScenes.living_scenes.action.on`) muss getriggert werden.

**Comment by mcbirne** [comment]
Ich triggere den action.on punkt über bloggly mit aktuealisiere. Ich setze den Wert auf wahr. 
Der Wert wird auch bei den Objekten geändert, aber auf der Bridge nicht.

![Unbenannt](https://user-images.githubusercontent.com/38691204/94705383-4593be00-0341-11eb-9734-301cfb060a99.PNG)

![Unbenann1](https://user-images.githubusercontent.com/38691204/94706006-f437fe80-0341-11eb-955a-d85415cfb5a5.PNG)

**Comment by Zefau** [comment]
Stell mal bitte die Instanz auf Debug und poste das Log, wenn du den Datenpunkt änderst.

**Comment by Zefau** [comment]
Und nur zur Sicherheit: die direkte Änderung ohne dein Skript geht auch nicht?

**Comment by mcbirne** [comment]
Wenn ich den Wert manuell ändere also true oder false reinschreibe wird das auch nicht übernommen. Wie kann ich es auf debug setzen?

**Comment by mcbirne** [comment]
Das steht nach dem ausführen des skriptes bei den Objekten
![Unbenannt3](https://user-images.githubusercontent.com/38691204/94716295-ea68c800-034e-11eb-8be3-879c88252784.PNG)
Aber die Lampen sind nicht an und in der Bridge ist der wwer auch nicht aktualisiert.

**Comment by Zefau** [comment]
Unter Instanzen -> Expertenansicht und dann gibt es dort ein Dropdown. Dort kann debug eingestellt werden.

**Comment by Zefau** [comment]
Welche Version des Adapters hast du im Einsatz?

**Comment by Zefau** [comment]
Bitte mal die v2.0.1 probieren. Habe vergessen, die ins latest zu schubsen. Einfach von Github installieren.

**Comment by mcbirne** [comment]
Die habe ich schon drauf...

**Comment by mcbirne** [comment]
Die Debugausgabe schaffe ich erst morgen. Reicht es Hue extended auf debug zu ändern?

**Comment by Zefau** [comment]
Jo

**Comment by mcbirne** [comment]
so viele Infos sehen im Log nicht
![Unbenannt2](https://user-images.githubusercontent.com/38691204/94799092-e5555880-03e2-11eb-9ce8-4ca04fb4b478.PNG)

**Comment by mcbirne** [comment]
Ich habe gerade festgestellt, dass wenn ich den Wert manuell ändere (nicht true oder false reinschreibe, sondern darau klicke), dann funktioniert es. Nur über das Script scheinbar nicht.

**Comment by mcbirne** [comment]
Es Funktionier!
Ich habe folgendes gemacht:
  Ich habe https eingeschaltet. Danach dann der Erfolg von oben beschrieben.
  Dann habe ich noch bei dem Blockly aus aktualisiere steuere gemacht. 

HTTPS war die Lösung. Danke für die Unterstützung
