### ISSUE TITLE
change sensor state

### ISSUE THREAD

**Issue by mcbirne** [Zefau/ioBroker.hue-extended#81]
If I change the state of an sensor nothing happens. I will change the state of an sensor like sensors/sensorname/state/flag to true or false. But if I change the value it doesn't have any effect to the value of the senor in the app.

**Comment by mcbirne** [comment]
Auch hier ist es so, dass der Adapter den Wert nicht auf der Bridge aktualisiert, sondern nur auf den Objekten. Ist das ein Bug oder ist es ein Featurewunsch?

**Comment by Zefau** [comment]
Auch hier ist `.action.on` zu triggern.

**Comment by mcbirne** [comment]
Gleiche wie bei dem anderen. Der Wert ändert sich nicht auf der Bridge

**Comment by mcbirne** [comment]
funktioniert nach Umstellung auf https auch
