### ISSUE TITLE
Hue Labs broken?

### ISSUE THREAD

**Issue by Scotty-89** [Zefau/ioBroker.hue-extended#83]
Hallo zusammen,

ich bin auf diesen Adapter eigentlich umgestiegen da ich damit die Hue Labs Geschichten schalten konnte..
leider war das ein konnte.. das geht jetzt seltsamer weise nicht mehr. Ich setzte den den Switch auf true aber nicht passiert.

Die einzelnen Lampen etc. kann ich normal steuern.

ist das bekannt ? 

mach ich ggf was falsch ? 

Vielen Dank.

**Comment by Zefau** [comment]
Siehe https://github.com/Zefau/ioBroker.hue-extended/issues/80. Geht es damit?

**Comment by Scotty-89** [comment]
Hallo,

habe jetzt auch mal auf Https umgestellt bzw. Default Zertifikat, Schlüssel und Passwort eingegeben (was auch immer da hinter steht...) und nun geht es nachdem ich die Scenen in Hue Lab neu angelegt habe..

seltsam  ich werde das mal beobachten ob es die nächste Tage auch weiterhin geht.

DANKE
