### ISSUE TITLE
IMPROVEMENT : ct should be also converted to xy 

### ISSUE THREAD

**Issue by dercaptainbc** [Zefau/ioBroker.hue-extended#9]
Because of ct values is not available for IKEA Tradfri Color Bulbs it should be possible to convert the ct values from group to xy value in case of ct is not there (like IKEA Tradfri Color Bulbs). 

Its not a bug its more an improvement for the next versions of the adapter. I guess it would be very useful for groups with contains hue and ikea bulbs (like in my bathroom :smile: )

**Comment by Zefau** [comment]
Sounds interesting. I will have a look at that.

**Comment by Zefau** [comment]
Please try and install `v1.1.5` from Github and upload the adapter.

This adds an option to the adapter settings for the conversion of `ct` to `xy`.
The conversion itself probably needs some more adjusting. Please test and try this.

**Comment by dercaptainbc** [comment]
Very cool! So far I can say it works as expected for me.

**Comment by dercaptainbc** [comment]
I've realized in my living room where only hue color lamps (Model : LCT0015) that here the adapter also set xy values instead of ct. Sorry but I need to reopen the issue. :-/

**Comment by Zefau** [comment]
What value does the state `manufacturername` of that lamps hold?

**Comment by Zefau** [comment]
damn, just realized that groups don't have that, only lights. :(

**Comment by Zefau** [comment]
@dercaptainbc could you try this again with the current Github version?

If a group contains at least one non-Philips light, the adapter will use `xy`. If it's only Philips lights, it will use the provided commands, e.g. `hue`.

**Comment by dercaptainbc** [comment]
For groups with only Philips lights the adapter still use XY and not ct

Quelle|Zeit|debug|Meldung
-- | -- | -- | --
hue-extended.0 | 2019-11-03 10:27:45.266 | debug | (7060) Successfully set /groups/8/action/xy on Schreibtisch (to 0.4198,0.3652).
hue-extended.0 | 2019-11-03 10:27:45.196 | debug | (7060) Attempt 1x - Send commands to Schreibtisch (groups/8/action): {"xy":[0.4198,0.3652]}.
hue-extended.0 | 2019-11-03 10:27:45.193 | debug | (7060) State of hue-extended.0.groups.008-schreibtisch.action._commands has changed {"val":"{\"ct\":250}","ack":false,"ts":1572773265188,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin

**Comment by Zefau** [comment]
Could you try the current version from Github once again? I think I finally fixed that one now. Thanks!

**Comment by Zefau** [comment]
@dercaptainbc Have you had the chance to verify this one? Thanks!

**Comment by dercaptainbc** [comment]
Yes! For me it looks fine. CT values have been used for Groups with only Philips lamps.
