### ISSUE TITLE
Command Queue Performanz & Light State Update delay

### ISSUE THREAD

**Issue by tops4u** [Zefau/ioBroker.hue-extended#92]
Ich verwende den Adapter erst seit kurzem. Ich wollte eigentlich die eingebauten 230V Schalter über einen Shelly verwenden um damit die HUE Deckenlampen gezielt ein und auszusschalten. Leider scheint es dabei 2 Probleme zu geben. 

Damit ich weiss welchen Status die Lampe hat muss ich diesen erst abfragen. Wurde die Lampe jedoch von der Fernbedienung oder etwas anderem erst gerade geschaltet, dann vergeht oft eine längere Zeit, bis die States updated werden. Schalte ich also über die Fernbedienung das Licht dauert es mehrere Sekunden (denke den Timer für den Aufbau aller States wie GET) und es kommt zu einem Missmatch wenn ich dann noch den HW-Schalter drücke. Wäre es nicht möglich die relevanten States der Lights öfters zu updaten als den gesamten Objektbaum? Gibt es da keinen CallBack von der Bridge? Ich habe mich nicht im Detail mit der HUE API befasst (habe auch keinen Account dort). Deshalb einfach meine doofe Frage. 

Wenn ich direkt auf einen State einwirke, dann wird der auch recht flott zur Bridge übertragen. Bei einer CommandQueue vergeht aber komischerweise einige Zeit bis da was passiert. Dabei könnte der erste Command sofort geschickt werden. Im angehängten Beispielt dauert es ca 1.5sec bis das passiert, obwohl die Kette Schalter -> Shelly via MQTT -> Node Red -> HueAdapter in Sekundenbruchteilen vor sich geht. 

![HUE_ExtendedDelay](https://user-images.githubusercontent.com/6877067/98248937-eb0c0400-1f75-11eb-9627-54471a6b3b1d.jpg)

**Comment by Zefau** [comment]
Wie sind deine Adapter Einstellungen?

**Comment by tops4u** [comment]
Bitte sehr: 

![image](https://user-images.githubusercontent.com/6877067/98268141-74c6cc00-1f8c-11eb-8804-8e6bd0256cea.png)

**Comment by Zefau** [comment]
Benutze warteschlange raus, dann gehts schneller. Oder Wert verändern.

Die Option meint, dass Befehle 3 Sekunden gesammelt und konsolidiert verschickt werden.

**Comment by tops4u** [comment]
Ah wunderbar. Im Log finde ich diesen Hinweis: Using polling for state updates 

Gibt es auch die Möglichkeit von Callbacks?

**Comment by Zefau** [comment]
Leider nein. Die Hue Bridge supported nur polling. Der Conbee/deconz Stick supported Callbacks bzw. Webhooks.

**Comment by tops4u** [comment]
Performance wurde besser.
